# Generated by Django 5.0.6 on 2024-06-19 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testadl", "0003_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Direccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calle", models.CharField(max_length=100)),
                ("numero", models.CharField(max_length=10)),
                ("dpto", models.CharField(blank=True, max_length=10, null=True)),
                ("comuna", models.CharField(max_length=100)),
                ("ciudad", models.CharField(max_length=100)),
                (
                    "cliente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testadl.cliente",
                    ),
                ),
            ],
        ),
    ]
